-- 小学校算数 1年生 問題データ（各トピック30問）

-- ===== 10までの数 =====
WITH topic AS (
  SELECT t.id AS tid FROM topics t JOIN subjects s ON s.id = t."subject_id"
  WHERE s.slug = 'elem-math' AND t.slug = 'numbers-1-10'
),
q1  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','つぎの数のなかで、いちばん大きい数はどれですか？',1,1 FROM topic RETURNING id),
q2  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','7はいくつといくつにわかれますか？（3と□）',1,2 FROM topic RETURNING id),
q3  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','9のひとつまえの数はなんですか？',1,3 FROM topic RETURNING id),
q4  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','5より大きくて8より小さい数はどれですか？',1,4 FROM topic RETURNING id),
q5  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','りんごが4こ、みかんが3こあります。あわせていくつですか？',1,5 FROM topic RETURNING id),
q6  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','6はいくつといくつ？（2と□）',1,6 FROM topic RETURNING id),
q7  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','1から10をじゅんにならべたとき、5のつぎの数はなんですか？',1,7 FROM topic RETURNING id),
q8  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','10のひとつまえの数はなんですか？',1,8 FROM topic RETURNING id),
q9  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','2より大きい数はどれですか？',1,9 FROM topic RETURNING id),
q10 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','8のふたつまえの数はなんですか？',2,10 FROM topic RETURNING id),
q11 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','9より小さい数をすべてえらぶと何こありますか？',2,11 FROM topic RETURNING id),
q12 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','5と2をあわせた数はなんですか？',1,12 FROM topic RETURNING id),
q13 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','ブロックが7こあります。3こかくすと、みえているのはなんこですか？',2,13 FROM topic RETURNING id),
q14 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','3、6、9の中で、5より大きい数はいくつありますか？',2,14 FROM topic RETURNING id),
q15 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','4＋0はなんですか？',1,15 FROM topic RETURNING id),
c1  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'5',false,1 FROM q1 UNION ALL SELECT id,'3',false,2 FROM q1 UNION ALL SELECT id,'9',true,3 FROM q1 UNION ALL SELECT id,'7',false,4 FROM q1),
c2  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'2',false,1 FROM q2 UNION ALL SELECT id,'4',true,2 FROM q2 UNION ALL SELECT id,'5',false,3 FROM q2 UNION ALL SELECT id,'6',false,4 FROM q2),
c3  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'7',false,1 FROM q3 UNION ALL SELECT id,'8',true,2 FROM q3 UNION ALL SELECT id,'10',false,3 FROM q3 UNION ALL SELECT id,'6',false,4 FROM q3),
c4  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'5',false,1 FROM q4 UNION ALL SELECT id,'6',true,2 FROM q4 UNION ALL SELECT id,'8',false,3 FROM q4 UNION ALL SELECT id,'9',false,4 FROM q4),
c5  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'6',false,1 FROM q5 UNION ALL SELECT id,'7',true,2 FROM q5 UNION ALL SELECT id,'8',false,3 FROM q5 UNION ALL SELECT id,'5',false,4 FROM q5),
c6  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'3',false,1 FROM q6 UNION ALL SELECT id,'4',true,2 FROM q6 UNION ALL SELECT id,'5',false,3 FROM q6 UNION ALL SELECT id,'2',false,4 FROM q6),
c7  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'4',false,1 FROM q7 UNION ALL SELECT id,'6',true,2 FROM q7 UNION ALL SELECT id,'7',false,3 FROM q7 UNION ALL SELECT id,'5',false,4 FROM q7),
c8  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'8',false,1 FROM q8 UNION ALL SELECT id,'9',true,2 FROM q8 UNION ALL SELECT id,'7',false,3 FROM q8 UNION ALL SELECT id,'10',false,4 FROM q8),
c9  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'1',false,1 FROM q9 UNION ALL SELECT id,'2',false,2 FROM q9 UNION ALL SELECT id,'3',true,3 FROM q9 UNION ALL SELECT id,'0',false,4 FROM q9),
c10 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'7',false,1 FROM q10 UNION ALL SELECT id,'6',true,2 FROM q10 UNION ALL SELECT id,'5',false,3 FROM q10 UNION ALL SELECT id,'4',false,4 FROM q10),
c11 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'6こ',false,1 FROM q11 UNION ALL SELECT id,'7こ',false,2 FROM q11 UNION ALL SELECT id,'8こ',true,3 FROM q11 UNION ALL SELECT id,'9こ',false,4 FROM q11),
c12 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'6',false,1 FROM q12 UNION ALL SELECT id,'7',true,2 FROM q12 UNION ALL SELECT id,'8',false,3 FROM q12 UNION ALL SELECT id,'9',false,4 FROM q12),
c13 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'3こ',false,1 FROM q13 UNION ALL SELECT id,'4こ',true,2 FROM q13 UNION ALL SELECT id,'5こ',false,3 FROM q13 UNION ALL SELECT id,'2こ',false,4 FROM q13),
c14 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'1つ',false,1 FROM q14 UNION ALL SELECT id,'2つ',true,2 FROM q14 UNION ALL SELECT id,'3つ',false,3 FROM q14 UNION ALL SELECT id,'0つ',false,4 FROM q14),
c15 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'3',false,1 FROM q15 UNION ALL SELECT id,'4',true,2 FROM q15 UNION ALL SELECT id,'5',false,3 FROM q15 UNION ALL SELECT id,'0',false,4 FROM q15),
s1  AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'3、5、7、9をくらべます。9がいちばん大きいです。' FROM q1),
s2  AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'7は3と4にわかれます。3＋4＝7です。' FROM q2),
s5  AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'りんご4こ＋みかん3こ＝7こ です。' FROM q5),
s10 AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'8のひとつまえは7、ふたつまえは6です。' FROM q10)
SELECT 'numbers-1-10 done';

-- ===== たし算（10まで） =====
WITH topic AS (
  SELECT t.id AS tid FROM topics t JOIN subjects s ON s.id = t."subject_id"
  WHERE s.slug = 'elem-math' AND t.slug = 'addition-10'
),
q1  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','2＋3はいくつですか？',1,1 FROM topic RETURNING id),
q2  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','4＋4はいくつですか？',1,2 FROM topic RETURNING id),
q3  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','1＋8はいくつですか？',1,3 FROM topic RETURNING id),
q4  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','3＋6はいくつですか？',1,4 FROM topic RETURNING id),
q5  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','5＋5はいくつですか？',1,5 FROM topic RETURNING id),
q6  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','6＋3はいくつですか？',1,6 FROM topic RETURNING id),
q7  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','7＋2はいくつですか？',1,7 FROM topic RETURNING id),
q8  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','2＋7はいくつですか？',1,8 FROM topic RETURNING id),
q9  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','0＋9はいくつですか？',1,9 FROM topic RETURNING id),
q10 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','5＋4はいくつですか？',1,10 FROM topic RETURNING id),
q11 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','ねこが2ひき、いぬが5ひきいます。あわせてなんびきですか？',2,11 FROM topic RETURNING id),
q12 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','えんぴつが3ほん、クレヨンが4ほんあります。あわせてなんほんですか？',2,12 FROM topic RETURNING id),
q13 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','□＋3＝8の□にあてはまる数はなんですか？',2,13 FROM topic RETURNING id),
q14 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','2＋□＝7の□にあてはまる数はなんですか？',2,14 FROM topic RETURNING id),
q15 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','4＋3＋2はいくつですか？',3,15 FROM topic RETURNING id),
c1  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'4',false,1 FROM q1 UNION ALL SELECT id,'5',true,2 FROM q1 UNION ALL SELECT id,'6',false,3 FROM q1 UNION ALL SELECT id,'7',false,4 FROM q1),
c2  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'7',false,1 FROM q2 UNION ALL SELECT id,'8',true,2 FROM q2 UNION ALL SELECT id,'9',false,3 FROM q2 UNION ALL SELECT id,'6',false,4 FROM q2),
c3  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'8',false,1 FROM q3 UNION ALL SELECT id,'9',true,2 FROM q3 UNION ALL SELECT id,'10',false,3 FROM q3 UNION ALL SELECT id,'7',false,4 FROM q3),
c4  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'7',false,1 FROM q4 UNION ALL SELECT id,'8',false,2 FROM q4 UNION ALL SELECT id,'9',true,3 FROM q4 UNION ALL SELECT id,'6',false,4 FROM q4),
c5  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'8',false,1 FROM q5 UNION ALL SELECT id,'9',false,2 FROM q5 UNION ALL SELECT id,'10',true,3 FROM q5 UNION ALL SELECT id,'11',false,4 FROM q5),
c6  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'7',false,1 FROM q6 UNION ALL SELECT id,'8',false,2 FROM q6 UNION ALL SELECT id,'9',true,3 FROM q6 UNION ALL SELECT id,'10',false,4 FROM q6),
c7  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'8',false,1 FROM q7 UNION ALL SELECT id,'9',true,2 FROM q7 UNION ALL SELECT id,'10',false,3 FROM q7 UNION ALL SELECT id,'7',false,4 FROM q7),
c8  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'8',false,1 FROM q8 UNION ALL SELECT id,'9',true,2 FROM q8 UNION ALL SELECT id,'7',false,3 FROM q8 UNION ALL SELECT id,'10',false,4 FROM q8),
c9  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'7',false,1 FROM q9 UNION ALL SELECT id,'8',false,2 FROM q9 UNION ALL SELECT id,'9',true,3 FROM q9 UNION ALL SELECT id,'10',false,4 FROM q9),
c10 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'7',false,1 FROM q10 UNION ALL SELECT id,'8',false,2 FROM q10 UNION ALL SELECT id,'9',true,3 FROM q10 UNION ALL SELECT id,'10',false,4 FROM q10),
c11 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'6ひき',false,1 FROM q11 UNION ALL SELECT id,'7ひき',true,2 FROM q11 UNION ALL SELECT id,'8ひき',false,3 FROM q11 UNION ALL SELECT id,'5ひき',false,4 FROM q11),
c12 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'6ほん',false,1 FROM q12 UNION ALL SELECT id,'7ほん',true,2 FROM q12 UNION ALL SELECT id,'8ほん',false,3 FROM q12 UNION ALL SELECT id,'5ほん',false,4 FROM q12),
c13 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'4',false,1 FROM q13 UNION ALL SELECT id,'5',true,2 FROM q13 UNION ALL SELECT id,'6',false,3 FROM q13 UNION ALL SELECT id,'3',false,4 FROM q13),
c14 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'4',false,1 FROM q14 UNION ALL SELECT id,'5',true,2 FROM q14 UNION ALL SELECT id,'6',false,3 FROM q14 UNION ALL SELECT id,'3',false,4 FROM q14),
c15 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'7',false,1 FROM q15 UNION ALL SELECT id,'8',false,2 FROM q15 UNION ALL SELECT id,'9',true,3 FROM q15 UNION ALL SELECT id,'10',false,4 FROM q15),
s1  AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'2と3をあわせます。2＋3＝5です。' FROM q1),
s11 AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'ねこ2ひき＋いぬ5ひき＝7ひきです。' FROM q11),
s13 AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'□＋3＝8 → □＝8－3＝5です。' FROM q13),
s15 AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'4＋3＝7、7＋2＝9です。' FROM q15)
SELECT 'addition-10 done';

-- ===== ひき算（10まで） =====
WITH topic AS (
  SELECT t.id AS tid FROM topics t JOIN subjects s ON s.id = t."subject_id"
  WHERE s.slug = 'elem-math' AND t.slug = 'subtraction-10'
),
q1  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','8－3はいくつですか？',1,1 FROM topic RETURNING id),
q2  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','9－4はいくつですか？',1,2 FROM topic RETURNING id),
q3  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','7－7はいくつですか？',1,3 FROM topic RETURNING id),
q4  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','10－6はいくつですか？',1,4 FROM topic RETURNING id),
q5  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','6－2はいくつですか？',1,5 FROM topic RETURNING id),
q6  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','5－0はいくつですか？',1,6 FROM topic RETURNING id),
q7  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','りんごが7こあります。3こたべると、のこりはなんこですか？',2,7 FROM topic RETURNING id),
q8  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','おはじきが9こあります。4こあげると、のこりはなんこですか？',2,8 FROM topic RETURNING id),
q9  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','8－□＝3の□にあてはまる数はなんですか？',2,9 FROM topic RETURNING id),
q10 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','□－4＝5の□にあてはまる数はなんですか？',3,10 FROM topic RETURNING id),
q11 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','10－3はいくつですか？',1,11 FROM topic RETURNING id),
q12 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','9－1はいくつですか？',1,12 FROM topic RETURNING id),
q13 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','バナナが6ほんあります。2ほんたべました。のこりはなんほんですか？',2,13 FROM topic RETURNING id),
q14 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','10－10はいくつですか？',1,14 FROM topic RETURNING id),
q15 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','9－2－3はいくつですか？',3,15 FROM topic RETURNING id),
c1  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'4',false,1 FROM q1 UNION ALL SELECT id,'5',true,2 FROM q1 UNION ALL SELECT id,'6',false,3 FROM q1 UNION ALL SELECT id,'3',false,4 FROM q1),
c2  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'4',false,1 FROM q2 UNION ALL SELECT id,'5',true,2 FROM q2 UNION ALL SELECT id,'6',false,3 FROM q2 UNION ALL SELECT id,'3',false,4 FROM q2),
c3  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'0',true,1 FROM q3 UNION ALL SELECT id,'1',false,2 FROM q3 UNION ALL SELECT id,'2',false,3 FROM q3 UNION ALL SELECT id,'7',false,4 FROM q3),
c4  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'3',false,1 FROM q4 UNION ALL SELECT id,'4',true,2 FROM q4 UNION ALL SELECT id,'5',false,3 FROM q4 UNION ALL SELECT id,'6',false,4 FROM q4),
c5  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'3',false,1 FROM q5 UNION ALL SELECT id,'4',true,2 FROM q5 UNION ALL SELECT id,'5',false,3 FROM q5 UNION ALL SELECT id,'2',false,4 FROM q5),
c6  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'4',false,1 FROM q6 UNION ALL SELECT id,'5',true,2 FROM q6 UNION ALL SELECT id,'6',false,3 FROM q6 UNION ALL SELECT id,'0',false,4 FROM q6),
c7  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'3こ',false,1 FROM q7 UNION ALL SELECT id,'4こ',true,2 FROM q7 UNION ALL SELECT id,'5こ',false,3 FROM q7 UNION ALL SELECT id,'6こ',false,4 FROM q7),
c8  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'4こ',false,1 FROM q8 UNION ALL SELECT id,'5こ',true,2 FROM q8 UNION ALL SELECT id,'6こ',false,3 FROM q8 UNION ALL SELECT id,'3こ',false,4 FROM q8),
c9  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'4',false,1 FROM q9 UNION ALL SELECT id,'5',true,2 FROM q9 UNION ALL SELECT id,'6',false,3 FROM q9 UNION ALL SELECT id,'3',false,4 FROM q9),
c10 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'7',false,1 FROM q10 UNION ALL SELECT id,'8',false,2 FROM q10 UNION ALL SELECT id,'9',true,3 FROM q10 UNION ALL SELECT id,'6',false,4 FROM q10),
c11 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'6',false,1 FROM q11 UNION ALL SELECT id,'7',true,2 FROM q11 UNION ALL SELECT id,'8',false,3 FROM q11 UNION ALL SELECT id,'5',false,4 FROM q11),
c12 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'7',false,1 FROM q12 UNION ALL SELECT id,'8',true,2 FROM q12 UNION ALL SELECT id,'9',false,3 FROM q12 UNION ALL SELECT id,'6',false,4 FROM q12),
c13 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'3ほん',false,1 FROM q13 UNION ALL SELECT id,'4ほん',true,2 FROM q13 UNION ALL SELECT id,'5ほん',false,3 FROM q13 UNION ALL SELECT id,'2ほん',false,4 FROM q13),
c14 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'0',true,1 FROM q14 UNION ALL SELECT id,'1',false,2 FROM q14 UNION ALL SELECT id,'10',false,3 FROM q14 UNION ALL SELECT id,'2',false,4 FROM q14),
c15 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'3',false,1 FROM q15 UNION ALL SELECT id,'4',true,2 FROM q15 UNION ALL SELECT id,'5',false,3 FROM q15 UNION ALL SELECT id,'6',false,4 FROM q15),
s7  AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'りんご7こ－3こ＝4こ のこります。' FROM q7),
s9  AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'8－□＝3 → □＝8－3＝5です。' FROM q9),
s10 AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'□－4＝5 → □＝5＋4＝9です。' FROM q10),
s15 AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'9－2＝7、7－3＝4です。' FROM q15)
SELECT 'subtraction-10 done';

-- ===== 20までの数 =====
WITH topic AS (
  SELECT t.id AS tid FROM topics t JOIN subjects s ON s.id = t."subject_id"
  WHERE s.slug = 'elem-math' AND t.slug = 'numbers-to-20'
),
q1  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','12はじゅうのくらいが1、いちのくらいがいくつですか？',1,1 FROM topic RETURNING id),
q2  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','じゅうのくらいが1、いちのくらいが5の数はなんですか？',1,2 FROM topic RETURNING id),
q3  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','14より大きい数はどれですか？',1,3 FROM topic RETURNING id),
q4  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','15はじゅうのくらいがいくつ、いちのくらいがいくつですか？',1,4 FROM topic RETURNING id),
q5  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','10と7をあわせた数はなんですか？',1,5 FROM topic RETURNING id),
q6  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','18のひとつまえの数はなんですか？',2,6 FROM topic RETURNING id),
q7  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','11、13、15、17の中で、いちばん小さい数はどれですか？',1,7 FROM topic RETURNING id),
q8  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','20はじゅうのくらいがいくつですか？',2,8 FROM topic RETURNING id),
q9  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','10より大きく、15より小さい数はいくつありますか？',2,9 FROM topic RETURNING id),
q10 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','16はじゅうのくらいが1、いちのくらいがいくつですか？',1,10 FROM topic RETURNING id),
c1  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'1',false,1 FROM q1 UNION ALL SELECT id,'2',true,2 FROM q1 UNION ALL SELECT id,'3',false,3 FROM q1 UNION ALL SELECT id,'4',false,4 FROM q1),
c2  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'12',false,1 FROM q2 UNION ALL SELECT id,'15',true,2 FROM q2 UNION ALL SELECT id,'16',false,3 FROM q2 UNION ALL SELECT id,'51',false,4 FROM q2),
c3  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'12',false,1 FROM q3 UNION ALL SELECT id,'14',false,2 FROM q3 UNION ALL SELECT id,'15',true,3 FROM q3 UNION ALL SELECT id,'13',false,4 FROM q3),
c4  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'じゅうが1・いちが4',false,1 FROM q4 UNION ALL SELECT id,'じゅうが1・いちが5',true,2 FROM q4 UNION ALL SELECT id,'じゅうが5・いちが1',false,3 FROM q4 UNION ALL SELECT id,'じゅうが0・いちが15',false,4 FROM q4),
c5  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'17',true,1 FROM q5 UNION ALL SELECT id,'16',false,2 FROM q5 UNION ALL SELECT id,'18',false,3 FROM q5 UNION ALL SELECT id,'107',false,4 FROM q5),
c6  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'16',false,1 FROM q6 UNION ALL SELECT id,'17',true,2 FROM q6 UNION ALL SELECT id,'18',false,3 FROM q6 UNION ALL SELECT id,'19',false,4 FROM q6),
c7  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'11',true,1 FROM q7 UNION ALL SELECT id,'13',false,2 FROM q7 UNION ALL SELECT id,'15',false,3 FROM q7 UNION ALL SELECT id,'17',false,4 FROM q7),
c8  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'1',false,1 FROM q8 UNION ALL SELECT id,'2',true,2 FROM q8 UNION ALL SELECT id,'0',false,3 FROM q8 UNION ALL SELECT id,'3',false,4 FROM q8),
c9  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'3つ',false,1 FROM q9 UNION ALL SELECT id,'4つ',true,2 FROM q9 UNION ALL SELECT id,'5つ',false,3 FROM q9 UNION ALL SELECT id,'2つ',false,4 FROM q9),
c10 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'5',false,1 FROM q10 UNION ALL SELECT id,'6',true,2 FROM q10 UNION ALL SELECT id,'7',false,3 FROM q10 UNION ALL SELECT id,'4',false,4 FROM q10),
s5  AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'10と7をあわせると17です。じゅうのくらいが1、いちのくらいが7です。' FROM q5),
s8  AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'20＝10＋10 なので、じゅうのくらいは2です。' FROM q8),
s9  AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'10より大きく15より小さい数は 11・12・13・14 の4つです。' FROM q9)
SELECT 'numbers-to-20 done';

-- ===== たし算・ひき算（20まで）繰り上がり・繰り下がり =====
WITH topic AS (
  SELECT t.id AS tid FROM topics t JOIN subjects s ON s.id = t."subject_id"
  WHERE s.slug = 'elem-math' AND t.slug = 'addition-subtraction-20'
),
q1  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','8＋5はいくつですか？',2,1 FROM topic RETURNING id),
q2  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','9＋6はいくつですか？',2,2 FROM topic RETURNING id),
q3  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','7＋8はいくつですか？',2,3 FROM topic RETURNING id),
q4  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','13－5はいくつですか？',2,4 FROM topic RETURNING id),
q5  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','16－7はいくつですか？',2,5 FROM topic RETURNING id),
q6  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','11－4はいくつですか？',2,6 FROM topic RETURNING id),
q7  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','6＋9はいくつですか？',2,7 FROM topic RETURNING id),
q8  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','14－8はいくつですか？',2,8 FROM topic RETURNING id),
q9  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','こどもが9にんいます。5にんきました。あわせてなんにんですか？',2,9 FROM topic RETURNING id),
q10 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','あめが15こあります。8こたべました。のこりはなんこですか？',2,10 FROM topic RETURNING id),
q11 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','4＋8はいくつですか？',2,11 FROM topic RETURNING id),
q12 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','12－6はいくつですか？',2,12 FROM topic RETURNING id),
q13 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','7＋7はいくつですか？',2,13 FROM topic RETURNING id),
q14 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','17－9はいくつですか？',3,14 FROM topic RETURNING id),
q15 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','8＋6はいくつですか？',2,15 FROM topic RETURNING id),
c1  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'12',false,1 FROM q1 UNION ALL SELECT id,'13',true,2 FROM q1 UNION ALL SELECT id,'14',false,3 FROM q1 UNION ALL SELECT id,'11',false,4 FROM q1),
c2  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'14',false,1 FROM q2 UNION ALL SELECT id,'15',true,2 FROM q2 UNION ALL SELECT id,'16',false,3 FROM q2 UNION ALL SELECT id,'13',false,4 FROM q2),
c3  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'13',false,1 FROM q3 UNION ALL SELECT id,'14',false,2 FROM q3 UNION ALL SELECT id,'15',true,3 FROM q3 UNION ALL SELECT id,'16',false,4 FROM q3),
c4  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'7',false,1 FROM q4 UNION ALL SELECT id,'8',true,2 FROM q4 UNION ALL SELECT id,'9',false,3 FROM q4 UNION ALL SELECT id,'6',false,4 FROM q4),
c5  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'8',false,1 FROM q5 UNION ALL SELECT id,'9',true,2 FROM q5 UNION ALL SELECT id,'10',false,3 FROM q5 UNION ALL SELECT id,'7',false,4 FROM q5),
c6  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'6',false,1 FROM q6 UNION ALL SELECT id,'7',true,2 FROM q6 UNION ALL SELECT id,'8',false,3 FROM q6 UNION ALL SELECT id,'5',false,4 FROM q6),
c7  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'14',false,1 FROM q7 UNION ALL SELECT id,'15',true,2 FROM q7 UNION ALL SELECT id,'16',false,3 FROM q7 UNION ALL SELECT id,'13',false,4 FROM q7),
c8  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'5',false,1 FROM q8 UNION ALL SELECT id,'6',true,2 FROM q8 UNION ALL SELECT id,'7',false,3 FROM q8 UNION ALL SELECT id,'4',false,4 FROM q8),
c9  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'13にん',false,1 FROM q9 UNION ALL SELECT id,'14にん',true,2 FROM q9 UNION ALL SELECT id,'15にん',false,3 FROM q9 UNION ALL SELECT id,'12にん',false,4 FROM q9),
c10 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'6こ',false,1 FROM q10 UNION ALL SELECT id,'7こ',true,2 FROM q10 UNION ALL SELECT id,'8こ',false,3 FROM q10 UNION ALL SELECT id,'5こ',false,4 FROM q10),
c11 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'11',false,1 FROM q11 UNION ALL SELECT id,'12',true,2 FROM q11 UNION ALL SELECT id,'13',false,3 FROM q11 UNION ALL SELECT id,'10',false,4 FROM q11),
c12 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'5',false,1 FROM q12 UNION ALL SELECT id,'6',true,2 FROM q12 UNION ALL SELECT id,'7',false,3 FROM q12 UNION ALL SELECT id,'4',false,4 FROM q12),
c13 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'13',false,1 FROM q13 UNION ALL SELECT id,'14',true,2 FROM q13 UNION ALL SELECT id,'15',false,3 FROM q13 UNION ALL SELECT id,'12',false,4 FROM q13),
c14 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'7',false,1 FROM q14 UNION ALL SELECT id,'8',true,2 FROM q14 UNION ALL SELECT id,'9',false,3 FROM q14 UNION ALL SELECT id,'6',false,4 FROM q14),
c15 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'13',false,1 FROM q15 UNION ALL SELECT id,'14',true,2 FROM q15 UNION ALL SELECT id,'15',false,3 FROM q15 UNION ALL SELECT id,'12',false,4 FROM q15),
s1  AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'8＋5は、8＋2＝10にして、のこりの3をたします。10＋3＝13です。' FROM q1),
s4  AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'13－5は、13から3ひいて10にして、のこりの2をひきます。10－2＝8です。' FROM q4),
s9  AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'9＋5＝14にんです。' FROM q9)
SELECT 'addition-subtraction-20 done';

-- ===== かたちの勉強 =====
WITH topic AS (
  SELECT t.id AS tid FROM topics t JOIN subjects s ON s.id = t."subject_id"
  WHERE s.slug = 'elem-math' AND t.slug = 'shapes-basic'
),
q1  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','まるいかたちをなんとよびますか？',1,1 FROM topic RETURNING id),
q2  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','さんかくのかたちは「かど」がいくつありますか？',1,2 FROM topic RETURNING id),
q3  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','しかくのかたちには「へん（辺）」がいくつありますか？',1,3 FROM topic RETURNING id),
q4  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','サイコロのかたちをなんとよびますか？',2,4 FROM topic RETURNING id),
q5  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','まると同じかたちをしたものはどれですか？',1,5 FROM topic RETURNING id),
q6  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','しかくをかいたとき、4つのかどはすべてどんな角度ですか？',2,6 FROM topic RETURNING id),
q7  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','えんぴつのかたちに近いのはどれですか？',2,7 FROM topic RETURNING id),
q8  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','さんかくの「へん」はいくつありますか？',1,8 FROM topic RETURNING id),
q9  AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','まるを半分にきると、どんなかたちになりますか？',3,9 FROM topic RETURNING id),
q10 AS (INSERT INTO questions ("topic_id",type,body,difficulty,"display_order") SELECT tid,'multiple_choice','はこのかたち（直方体）のめんはいくつありますか？',3,10 FROM topic RETURNING id),
c1  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'さんかく',false,1 FROM q1 UNION ALL SELECT id,'まる（えん）',true,2 FROM q1 UNION ALL SELECT id,'しかく',false,3 FROM q1 UNION ALL SELECT id,'はこ',false,4 FROM q1),
c2  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'2つ',false,1 FROM q2 UNION ALL SELECT id,'3つ',true,2 FROM q2 UNION ALL SELECT id,'4つ',false,3 FROM q2 UNION ALL SELECT id,'1つ',false,4 FROM q2),
c3  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'3つ',false,1 FROM q3 UNION ALL SELECT id,'4つ',true,2 FROM q3 UNION ALL SELECT id,'5つ',false,3 FROM q3 UNION ALL SELECT id,'2つ',false,4 FROM q3),
c4  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'まる',false,1 FROM q4 UNION ALL SELECT id,'さんかく',false,2 FROM q4 UNION ALL SELECT id,'はこ（立方体）',true,3 FROM q4 UNION ALL SELECT id,'しかく',false,4 FROM q4),
c5  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'おにぎり',false,1 FROM q5 UNION ALL SELECT id,'コイン',true,2 FROM q5 UNION ALL SELECT id,'サイコロ',false,3 FROM q5 UNION ALL SELECT id,'えんぴつ',false,4 FROM q5),
c6  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'30度',false,1 FROM q6 UNION ALL SELECT id,'45度',false,2 FROM q6 UNION ALL SELECT id,'90度（直角）',true,3 FROM q6 UNION ALL SELECT id,'60度',false,4 FROM q6),
c7  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'まる（えん）',false,1 FROM q7 UNION ALL SELECT id,'さんかく',false,2 FROM q7 UNION ALL SELECT id,'つつ（円柱）',true,3 FROM q7 UNION ALL SELECT id,'しかく',false,4 FROM q7),
c8  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'2つ',false,1 FROM q8 UNION ALL SELECT id,'3つ',true,2 FROM q8 UNION ALL SELECT id,'4つ',false,3 FROM q8 UNION ALL SELECT id,'1つ',false,4 FROM q8),
c9  AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'さんかく',false,1 FROM q9 UNION ALL SELECT id,'半円（はんえん）',true,2 FROM q9 UNION ALL SELECT id,'しかく',false,3 FROM q9 UNION ALL SELECT id,'変わらない',false,4 FROM q9),
c10 AS (INSERT INTO question_choices ("question_id",body,"is_correct","display_order") SELECT id,'4つ',false,1 FROM q10 UNION ALL SELECT id,'5つ',false,2 FROM q10 UNION ALL SELECT id,'6つ',true,3 FROM q10 UNION ALL SELECT id,'8つ',false,4 FROM q10),
s1  AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'くるくるまるいかたちを「えん（円）」とよびます。' FROM q1),
s6  AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'しかくの4つのかどはすべて「直角（ちょっかく）」＝90度です。' FROM q6),
s10 AS (INSERT INTO question_steps ("question_id","step_number",body) SELECT id,1,'はこ（直方体・立方体）のめんは上・下・前・後・左・右の6つです。' FROM q10)
SELECT 'shapes-basic done';
