-- 小学校算数 2年生 問題データ

-- ===== 2けたのたし算 =====
WITH topic AS (
  SELECT t.id AS tid FROM topics t JOIN subjects s ON s.id = t."subjectId"
  WHERE s.slug = 'elem-math' AND t.slug = 'addition-2digit'
),
q1  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','23＋14はいくつですか？',2,1 FROM topic RETURNING id),
q2  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','34＋25はいくつですか？',2,2 FROM topic RETURNING id),
q3  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','41＋36はいくつですか？',2,3 FROM topic RETURNING id),
q4  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','52＋17はいくつですか？',2,4 FROM topic RETURNING id),
q5  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','63＋24はいくつですか？',2,5 FROM topic RETURNING id),
q6  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','27＋35はいくつですか？（繰り上がりあり）',2,6 FROM topic RETURNING id),
q7  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','48＋36はいくつですか？（繰り上がりあり）',2,7 FROM topic RETURNING id),
q8  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','55＋28はいくつですか？（繰り上がりあり）',2,8 FROM topic RETURNING id),
q9  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','36＋47はいくつですか？（繰り上がりあり）',2,9 FROM topic RETURNING id),
q10 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','64＋29はいくつですか？（繰り上がりあり）',2,10 FROM topic RETURNING id),
q11 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','バスに23人乗っています。次の停留所で14人乗りました。バスには今何人いますか？',2,11 FROM topic RETURNING id),
q12 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','赤いビー玉が35こ、青いビー玉が27こあります。あわせて何こですか？',2,12 FROM topic RETURNING id),
q13 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','本だなに本が46さつあります。18さつ買いたしました。全部で何さつになりましたか？',2,13 FROM topic RETURNING id),
q14 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','公園に子どもが29人いました。そこへ33人来ました。全部で何人ですか？',2,14 FROM topic RETURNING id),
q15 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','みかんが57こあります。りんごが38こあります。あわせて何こですか？',2,15 FROM topic RETURNING id),
c1  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'36',false,1 FROM q1 UNION ALL SELECT id,'37',true,2 FROM q1 UNION ALL SELECT id,'38',false,3 FROM q1 UNION ALL SELECT id,'27',false,4 FROM q1),
c2  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'58',false,1 FROM q2 UNION ALL SELECT id,'59',true,2 FROM q2 UNION ALL SELECT id,'60',false,3 FROM q2 UNION ALL SELECT id,'57',false,4 FROM q2),
c3  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'76',false,1 FROM q3 UNION ALL SELECT id,'77',true,2 FROM q3 UNION ALL SELECT id,'78',false,3 FROM q3 UNION ALL SELECT id,'75',false,4 FROM q3),
c4  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'68',false,1 FROM q4 UNION ALL SELECT id,'69',true,2 FROM q4 UNION ALL SELECT id,'70',false,3 FROM q4 UNION ALL SELECT id,'67',false,4 FROM q4),
c5  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'86',false,1 FROM q5 UNION ALL SELECT id,'87',true,2 FROM q5 UNION ALL SELECT id,'88',false,3 FROM q5 UNION ALL SELECT id,'85',false,4 FROM q5),
c6  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'61',false,1 FROM q6 UNION ALL SELECT id,'62',true,2 FROM q6 UNION ALL SELECT id,'63',false,3 FROM q6 UNION ALL SELECT id,'52',false,4 FROM q6),
c7  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'83',false,1 FROM q7 UNION ALL SELECT id,'84',true,2 FROM q7 UNION ALL SELECT id,'85',false,3 FROM q7 UNION ALL SELECT id,'74',false,4 FROM q7),
c8  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'82',false,1 FROM q8 UNION ALL SELECT id,'83',true,2 FROM q8 UNION ALL SELECT id,'84',false,3 FROM q8 UNION ALL SELECT id,'73',false,4 FROM q8),
c9  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'82',false,1 FROM q9 UNION ALL SELECT id,'83',true,2 FROM q9 UNION ALL SELECT id,'84',false,3 FROM q9 UNION ALL SELECT id,'73',false,4 FROM q9),
c10 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'92',false,1 FROM q10 UNION ALL SELECT id,'93',true,2 FROM q10 UNION ALL SELECT id,'94',false,3 FROM q10 UNION ALL SELECT id,'83',false,4 FROM q10),
c11 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'36人',false,1 FROM q11 UNION ALL SELECT id,'37人',true,2 FROM q11 UNION ALL SELECT id,'38人',false,3 FROM q11 UNION ALL SELECT id,'27人',false,4 FROM q11),
c12 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'61こ',false,1 FROM q12 UNION ALL SELECT id,'62こ',true,2 FROM q12 UNION ALL SELECT id,'63こ',false,3 FROM q12 UNION ALL SELECT id,'52こ',false,4 FROM q12),
c13 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'63さつ',false,1 FROM q13 UNION ALL SELECT id,'64さつ',true,2 FROM q13 UNION ALL SELECT id,'65さつ',false,3 FROM q13 UNION ALL SELECT id,'54さつ',false,4 FROM q13),
c14 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'61人',false,1 FROM q14 UNION ALL SELECT id,'62人',true,2 FROM q14 UNION ALL SELECT id,'63人',false,3 FROM q14 UNION ALL SELECT id,'52人',false,4 FROM q14),
c15 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'94こ',false,1 FROM q15 UNION ALL SELECT id,'95こ',true,2 FROM q15 UNION ALL SELECT id,'96こ',false,3 FROM q15 UNION ALL SELECT id,'85こ',false,4 FROM q15),
s1  AS (INSERT INTO question_steps ("questionId","stepNumber",body) SELECT id,1,'一の位: 3＋4＝7、十の位: 2＋1＝3 → 37です。' FROM q1),
s6  AS (INSERT INTO question_steps ("questionId","stepNumber",body) SELECT id,1,'一の位: 7＋5＝12 → 2を書いて1繰り上がり。十の位: 2＋3＋1＝6 → 62です。' FROM q6),
s11 AS (INSERT INTO question_steps ("questionId","stepNumber",body) SELECT id,1,'23＋14＝37人です。' FROM q11),
s12 AS (INSERT INTO question_steps ("questionId","stepNumber",body) SELECT id,1,'一の位: 5＋7＝12 → 2を書いて1繰り上がり。十の位: 3＋2＋1＝6 → 62こです。' FROM q12)
SELECT 'addition-2digit done';

-- ===== 2けたのひき算 =====
WITH topic AS (
  SELECT t.id AS tid FROM topics t JOIN subjects s ON s.id = t."subjectId"
  WHERE s.slug = 'elem-math' AND t.slug = 'subtraction-2digit'
),
q1  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','56－23はいくつですか？',2,1 FROM topic RETURNING id),
q2  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','79－45はいくつですか？',2,2 FROM topic RETURNING id),
q3  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','88－34はいくつですか？',2,3 FROM topic RETURNING id),
q4  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','97－62はいくつですか？',2,4 FROM topic RETURNING id),
q5  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','65－21はいくつですか？',2,5 FROM topic RETURNING id),
q6  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','43－18はいくつですか？（繰り下がりあり）',2,6 FROM topic RETURNING id),
q7  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','72－45はいくつですか？（繰り下がりあり）',2,7 FROM topic RETURNING id),
q8  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','61－37はいくつですか？（繰り下がりあり）',2,8 FROM topic RETURNING id),
q9  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','54－28はいくつですか？（繰り下がりあり）',2,9 FROM topic RETURNING id),
q10 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','83－56はいくつですか？（繰り下がりあり）',2,10 FROM topic RETURNING id),
q11 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','えんぴつが74本あります。32本使いました。のこりは何本ですか？',2,11 FROM topic RETURNING id),
q12 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','シールが52まいあります。27まいあげました。のこりは何まいですか？',2,12 FROM topic RETURNING id),
q13 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','バスに63人乗っていました。45人降りました。のこりは何人ですか？',2,13 FROM topic RETURNING id),
q14 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','りんごが80こあります。36こ売れました。のこりは何こですか？',2,14 FROM topic RETURNING id),
q15 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','クラスに45人います。そのうち男子が23人です。女子は何人ですか？',2,15 FROM topic RETURNING id),
c1  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'32',false,1 FROM q1 UNION ALL SELECT id,'33',true,2 FROM q1 UNION ALL SELECT id,'34',false,3 FROM q1 UNION ALL SELECT id,'43',false,4 FROM q1),
c2  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'33',false,1 FROM q2 UNION ALL SELECT id,'34',true,2 FROM q2 UNION ALL SELECT id,'35',false,3 FROM q2 UNION ALL SELECT id,'24',false,4 FROM q2),
c3  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'53',false,1 FROM q3 UNION ALL SELECT id,'54',true,2 FROM q3 UNION ALL SELECT id,'55',false,3 FROM q3 UNION ALL SELECT id,'44',false,4 FROM q3),
c4  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'34',false,1 FROM q4 UNION ALL SELECT id,'35',true,2 FROM q4 UNION ALL SELECT id,'36',false,3 FROM q4 UNION ALL SELECT id,'25',false,4 FROM q4),
c5  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'43',false,1 FROM q5 UNION ALL SELECT id,'44',true,2 FROM q5 UNION ALL SELECT id,'45',false,3 FROM q5 UNION ALL SELECT id,'34',false,4 FROM q5),
c6  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'24',false,1 FROM q6 UNION ALL SELECT id,'25',true,2 FROM q6 UNION ALL SELECT id,'26',false,3 FROM q6 UNION ALL SELECT id,'35',false,4 FROM q6),
c7  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'26',false,1 FROM q7 UNION ALL SELECT id,'27',true,2 FROM q7 UNION ALL SELECT id,'28',false,3 FROM q7 UNION ALL SELECT id,'37',false,4 FROM q7),
c8  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'23',false,1 FROM q8 UNION ALL SELECT id,'24',true,2 FROM q8 UNION ALL SELECT id,'25',false,3 FROM q8 UNION ALL SELECT id,'34',false,4 FROM q8),
c9  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'25',false,1 FROM q9 UNION ALL SELECT id,'26',true,2 FROM q9 UNION ALL SELECT id,'27',false,3 FROM q9 UNION ALL SELECT id,'36',false,4 FROM q9),
c10 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'26',false,1 FROM q10 UNION ALL SELECT id,'27',true,2 FROM q10 UNION ALL SELECT id,'28',false,3 FROM q10 UNION ALL SELECT id,'37',false,4 FROM q10),
c11 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'41本',false,1 FROM q11 UNION ALL SELECT id,'42本',true,2 FROM q11 UNION ALL SELECT id,'43本',false,3 FROM q11 UNION ALL SELECT id,'32本',false,4 FROM q11),
c12 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'24まい',false,1 FROM q12 UNION ALL SELECT id,'25まい',true,2 FROM q12 UNION ALL SELECT id,'26まい',false,3 FROM q12 UNION ALL SELECT id,'35まい',false,4 FROM q12),
c13 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'17人',false,1 FROM q13 UNION ALL SELECT id,'18人',true,2 FROM q13 UNION ALL SELECT id,'19人',false,3 FROM q13 UNION ALL SELECT id,'28人',false,4 FROM q13),
c14 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'43こ',false,1 FROM q14 UNION ALL SELECT id,'44こ',true,2 FROM q14 UNION ALL SELECT id,'45こ',false,3 FROM q14 UNION ALL SELECT id,'54こ',false,4 FROM q14),
c15 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'21人',false,1 FROM q15 UNION ALL SELECT id,'22人',true,2 FROM q15 UNION ALL SELECT id,'23人',false,3 FROM q15 UNION ALL SELECT id,'12人',false,4 FROM q15),
s1  AS (INSERT INTO question_steps ("questionId","stepNumber",body) SELECT id,1,'一の位: 6－3＝3、十の位: 5－2＝3 → 33です。' FROM q1),
s6  AS (INSERT INTO question_steps ("questionId","stepNumber",body) SELECT id,1,'一の位: 3から8はひけないので十の位から1借りる。13－8＝5、十の位: 4－1－1＝2 → 25です。' FROM q6),
s12 AS (INSERT INTO question_steps ("questionId","stepNumber",body) SELECT id,1,'一の位: 2から7はひけないので十の位から1借りる。12－7＝5、十の位: 5－1－2＝2 → 25まいです。' FROM q12)
SELECT 'subtraction-2digit done';

-- ===== かけ算（九九） =====
WITH topic AS (
  SELECT t.id AS tid FROM topics t JOIN subjects s ON s.id = t."subjectId"
  WHERE s.slug = 'elem-math' AND t.slug = 'multiplication-table'
),
q1  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','2×3はいくつですか？',2,1 FROM topic RETURNING id),
q2  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','2×7はいくつですか？',2,2 FROM topic RETURNING id),
q3  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','3×4はいくつですか？',2,3 FROM topic RETURNING id),
q4  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','3×8はいくつですか？',2,4 FROM topic RETURNING id),
q5  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','4×5はいくつですか？',2,5 FROM topic RETURNING id),
q6  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','4×9はいくつですか？',2,6 FROM topic RETURNING id),
q7  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','5×6はいくつですか？',2,7 FROM topic RETURNING id),
q8  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','6×4はいくつですか？',2,8 FROM topic RETURNING id),
q9  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','6×7はいくつですか？',2,9 FROM topic RETURNING id),
q10 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','7×6はいくつですか？',2,10 FROM topic RETURNING id),
q11 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','7×8はいくつですか？',2,11 FROM topic RETURNING id),
q12 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','8×7はいくつですか？',2,12 FROM topic RETURNING id),
q13 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','8×9はいくつですか？',2,13 FROM topic RETURNING id),
q14 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','9×7はいくつですか？',2,14 FROM topic RETURNING id),
q15 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','9×9はいくつですか？',2,15 FROM topic RETURNING id),
q16 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','5×8はいくつですか？',2,16 FROM topic RETURNING id),
q17 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','3×6はいくつですか？',2,17 FROM topic RETURNING id),
q18 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','4×7はいくつですか？',2,18 FROM topic RETURNING id),
q19 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','6×8はいくつですか？',2,19 FROM topic RETURNING id),
q20 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','7×9はいくつですか？',2,20 FROM topic RETURNING id),
c1  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'5',false,1 FROM q1 UNION ALL SELECT id,'6',true,2 FROM q1 UNION ALL SELECT id,'7',false,3 FROM q1 UNION ALL SELECT id,'8',false,4 FROM q1),
c2  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'13',false,1 FROM q2 UNION ALL SELECT id,'14',true,2 FROM q2 UNION ALL SELECT id,'15',false,3 FROM q2 UNION ALL SELECT id,'16',false,4 FROM q2),
c3  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'11',false,1 FROM q3 UNION ALL SELECT id,'12',true,2 FROM q3 UNION ALL SELECT id,'13',false,3 FROM q3 UNION ALL SELECT id,'10',false,4 FROM q3),
c4  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'23',false,1 FROM q4 UNION ALL SELECT id,'24',true,2 FROM q4 UNION ALL SELECT id,'25',false,3 FROM q4 UNION ALL SELECT id,'21',false,4 FROM q4),
c5  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'18',false,1 FROM q5 UNION ALL SELECT id,'20',true,2 FROM q5 UNION ALL SELECT id,'22',false,3 FROM q5 UNION ALL SELECT id,'16',false,4 FROM q5),
c6  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'35',false,1 FROM q6 UNION ALL SELECT id,'36',true,2 FROM q6 UNION ALL SELECT id,'37',false,3 FROM q6 UNION ALL SELECT id,'32',false,4 FROM q6),
c7  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'28',false,1 FROM q7 UNION ALL SELECT id,'30',true,2 FROM q7 UNION ALL SELECT id,'32',false,3 FROM q7 UNION ALL SELECT id,'25',false,4 FROM q7),
c8  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'22',false,1 FROM q8 UNION ALL SELECT id,'24',true,2 FROM q8 UNION ALL SELECT id,'26',false,3 FROM q8 UNION ALL SELECT id,'20',false,4 FROM q8),
c9  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'40',false,1 FROM q9 UNION ALL SELECT id,'42',true,2 FROM q9 UNION ALL SELECT id,'44',false,3 FROM q9 UNION ALL SELECT id,'36',false,4 FROM q9),
c10 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'40',false,1 FROM q10 UNION ALL SELECT id,'42',true,2 FROM q10 UNION ALL SELECT id,'44',false,3 FROM q10 UNION ALL SELECT id,'36',false,4 FROM q10),
c11 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'54',false,1 FROM q11 UNION ALL SELECT id,'56',true,2 FROM q11 UNION ALL SELECT id,'58',false,3 FROM q11 UNION ALL SELECT id,'48',false,4 FROM q11),
c12 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'54',false,1 FROM q12 UNION ALL SELECT id,'56',true,2 FROM q12 UNION ALL SELECT id,'58',false,3 FROM q12 UNION ALL SELECT id,'48',false,4 FROM q12),
c13 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'70',false,1 FROM q13 UNION ALL SELECT id,'72',true,2 FROM q13 UNION ALL SELECT id,'74',false,3 FROM q13 UNION ALL SELECT id,'64',false,4 FROM q13),
c14 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'61',false,1 FROM q14 UNION ALL SELECT id,'63',true,2 FROM q14 UNION ALL SELECT id,'65',false,3 FROM q14 UNION ALL SELECT id,'54',false,4 FROM q14),
c15 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'80',false,1 FROM q15 UNION ALL SELECT id,'81',true,2 FROM q15 UNION ALL SELECT id,'82',false,3 FROM q15 UNION ALL SELECT id,'72',false,4 FROM q15),
c16 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'38',false,1 FROM q16 UNION ALL SELECT id,'40',true,2 FROM q16 UNION ALL SELECT id,'42',false,3 FROM q16 UNION ALL SELECT id,'35',false,4 FROM q16),
c17 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'16',false,1 FROM q17 UNION ALL SELECT id,'18',true,2 FROM q17 UNION ALL SELECT id,'20',false,3 FROM q17 UNION ALL SELECT id,'15',false,4 FROM q17),
c18 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'26',false,1 FROM q18 UNION ALL SELECT id,'28',true,2 FROM q18 UNION ALL SELECT id,'30',false,3 FROM q18 UNION ALL SELECT id,'24',false,4 FROM q18),
c19 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'46',false,1 FROM q19 UNION ALL SELECT id,'48',true,2 FROM q19 UNION ALL SELECT id,'50',false,3 FROM q19 UNION ALL SELECT id,'42',false,4 FROM q19),
c20 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'61',false,1 FROM q20 UNION ALL SELECT id,'63',true,2 FROM q20 UNION ALL SELECT id,'65',false,3 FROM q20 UNION ALL SELECT id,'56',false,4 FROM q20),
s3  AS (INSERT INTO question_steps ("questionId","stepNumber",body) SELECT id,1,'3の段: 3×1＝3、3×2＝6、3×3＝9、3×4＝12 です。' FROM q3),
s7  AS (INSERT INTO question_steps ("questionId","stepNumber",body) SELECT id,1,'5の段は5ずつ増えます。5×6＝30 です。' FROM q7),
s11 AS (INSERT INTO question_steps ("questionId","stepNumber",body) SELECT id,1,'7×8＝56 です。しちはごじゅうろく と覚えましょう。' FROM q11),
s15 AS (INSERT INTO question_steps ("questionId","stepNumber",body) SELECT id,1,'9×9＝81 です。くくはちじゅういち と覚えましょう。' FROM q15)
SELECT 'multiplication-table done';

-- ===== 長さ =====
WITH topic AS (
  SELECT t.id AS tid FROM topics t JOIN subjects s ON s.id = t."subjectId"
  WHERE s.slug = 'elem-math' AND t.slug = 'length-basic'
),
q1  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','1cmは何mmですか？',2,1 FROM topic RETURNING id),
q2  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','3cm5mmは何mmですか？',2,2 FROM topic RETURNING id),
q3  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','47mmは何cm何mmですか？',2,3 FROM topic RETURNING id),
q4  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','2cm＋3cmはいくつですか？',2,4 FROM topic RETURNING id),
q5  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','4cm5mm＋2cm3mmはいくつですか？',2,5 FROM topic RETURNING id),
q6  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','7cm－3cmはいくつですか？',2,6 FROM topic RETURNING id),
q7  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','8cm4mm－5cm1mmはいくつですか？',2,7 FROM topic RETURNING id),
q8  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','20mmは何cmですか？',2,8 FROM topic RETURNING id),
q9  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','えんぴつの長さが15cmです。消しゴムの長さが4cmです。えんぴつは消しゴムより何cm長いですか？',2,9 FROM topic RETURNING id),
q10 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','リボンが2本あります。1本は5cm8mm、もう1本は3cm4mmです。あわせて何cm何mmですか？',2,10 FROM topic RETURNING id),
c1  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'1mm',false,1 FROM q1 UNION ALL SELECT id,'10mm',true,2 FROM q1 UNION ALL SELECT id,'100mm',false,3 FROM q1 UNION ALL SELECT id,'5mm',false,4 FROM q1),
c2  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'30mm',false,1 FROM q2 UNION ALL SELECT id,'35mm',true,2 FROM q2 UNION ALL SELECT id,'38mm',false,3 FROM q2 UNION ALL SELECT id,'53mm',false,4 FROM q2),
c3  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'3cm7mm',false,1 FROM q3 UNION ALL SELECT id,'4cm7mm',true,2 FROM q3 UNION ALL SELECT id,'4cm3mm',false,3 FROM q3 UNION ALL SELECT id,'5cm7mm',false,4 FROM q3),
c4  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'4cm',false,1 FROM q4 UNION ALL SELECT id,'5cm',true,2 FROM q4 UNION ALL SELECT id,'6cm',false,3 FROM q4 UNION ALL SELECT id,'23cm',false,4 FROM q4),
c5  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'6cm7mm',false,1 FROM q5 UNION ALL SELECT id,'6cm8mm',true,2 FROM q5 UNION ALL SELECT id,'7cm0mm',false,3 FROM q5 UNION ALL SELECT id,'6cm5mm',false,4 FROM q5),
c6  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'3cm',false,1 FROM q6 UNION ALL SELECT id,'4cm',true,2 FROM q6 UNION ALL SELECT id,'5cm',false,3 FROM q6 UNION ALL SELECT id,'10cm',false,4 FROM q6),
c7  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'2cm2mm',false,1 FROM q7 UNION ALL SELECT id,'3cm3mm',true,2 FROM q7 UNION ALL SELECT id,'3cm5mm',false,3 FROM q7 UNION ALL SELECT id,'4cm3mm',false,4 FROM q7),
c8  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'1cm',false,1 FROM q8 UNION ALL SELECT id,'2cm',true,2 FROM q8 UNION ALL SELECT id,'5cm',false,3 FROM q8 UNION ALL SELECT id,'20cm',false,4 FROM q8),
c9  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'10cm',false,1 FROM q9 UNION ALL SELECT id,'11cm',true,2 FROM q9 UNION ALL SELECT id,'12cm',false,3 FROM q9 UNION ALL SELECT id,'19cm',false,4 FROM q9),
c10 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'8cm2mm',false,1 FROM q10 UNION ALL SELECT id,'9cm2mm',true,2 FROM q10 UNION ALL SELECT id,'9cm4mm',false,3 FROM q10 UNION ALL SELECT id,'8cm12mm',false,4 FROM q10),
s1  AS (INSERT INTO question_steps ("questionId","stepNumber",body) SELECT id,1,'1cm＝10mm です。これは必ず覚えましょう。' FROM q1),
s2  AS (INSERT INTO question_steps ("questionId","stepNumber",body) SELECT id,1,'3cm＝30mm、そこに5mmたすので、30＋5＝35mm です。' FROM q2),
s5  AS (INSERT INTO question_steps ("questionId","stepNumber",body) SELECT id,1,'cm同士、mm同士をたします。4＋2＝6cm、5＋3＝8mm → 6cm8mm です。' FROM q5)
SELECT 'length-basic done';

-- ===== 時刻と時間 =====
WITH topic AS (
  SELECT t.id AS tid FROM topics t JOIN subjects s ON s.id = t."subjectId"
  WHERE s.slug = 'elem-math' AND t.slug = 'time-basic'
),
q1  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','時計の長い針が12、短い針が3をさしています。何時ですか？',2,1 FROM topic RETURNING id),
q2  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','時計の長い針が6、短い針が8をさしています。何時何分ですか？',2,2 FROM topic RETURNING id),
q3  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','時計の長い針が3、短い針が10をさしています。何時何分ですか？',2,3 FROM topic RETURNING id),
q4  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','今は午前10時30分です。30分後は何時何分ですか？',2,4 FROM topic RETURNING id),
q5  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','今は午後2時45分です。15分後は何時何分ですか？',2,5 FROM topic RETURNING id),
q6  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','今は午前9時20分です。40分前は何時何分ですか？',2,6 FROM topic RETURNING id),
q7  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','今は午後3時10分です。50分前は何時何分ですか？',3,7 FROM topic RETURNING id),
q8  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','学校が午前8時30分に始まり、午後3時に終わります。何時間何分の授業ですか？',3,8 FROM topic RETURNING id),
q9  AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','映画が午後1時15分に始まり、午後3時15分に終わりました。映画は何時間でしたか？',2,9 FROM topic RETURNING id),
q10 AS (INSERT INTO questions ("topicId",type,body,difficulty,"displayOrder") SELECT tid,'multiple_choice','公園に午前10時に着いて、午前11時30分に帰りました。公園にいた時間は何時間何分ですか？',2,10 FROM topic RETURNING id),
c1  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'2時',false,1 FROM q1 UNION ALL SELECT id,'3時',true,2 FROM q1 UNION ALL SELECT id,'4時',false,3 FROM q1 UNION ALL SELECT id,'12時',false,4 FROM q1),
c2  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'8時3分',false,1 FROM q2 UNION ALL SELECT id,'8時30分',true,2 FROM q2 UNION ALL SELECT id,'6時8分',false,3 FROM q2 UNION ALL SELECT id,'8時6分',false,4 FROM q2),
c3  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'10時3分',false,1 FROM q3 UNION ALL SELECT id,'10時15分',true,2 FROM q3 UNION ALL SELECT id,'3時10分',false,3 FROM q3 UNION ALL SELECT id,'10時30分',false,4 FROM q3),
c4  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'10時50分',false,1 FROM q4 UNION ALL SELECT id,'11時0分',true,2 FROM q4 UNION ALL SELECT id,'11時30分',false,3 FROM q4 UNION ALL SELECT id,'10時0分',false,4 FROM q4),
c5  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'2時55分',false,1 FROM q5 UNION ALL SELECT id,'3時0分',true,2 FROM q5 UNION ALL SELECT id,'3時15分',false,3 FROM q5 UNION ALL SELECT id,'2時45分',false,4 FROM q5),
c6  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'8時30分',false,1 FROM q6 UNION ALL SELECT id,'8時40分',true,2 FROM q6 UNION ALL SELECT id,'9時0分',false,3 FROM q6 UNION ALL SELECT id,'8時20分',false,4 FROM q6),
c7  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'2時10分',false,1 FROM q7 UNION ALL SELECT id,'2時20分',true,2 FROM q7 UNION ALL SELECT id,'2時30分',false,3 FROM q7 UNION ALL SELECT id,'3時0分',false,4 FROM q7),
c8  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'5時間30分',false,1 FROM q8 UNION ALL SELECT id,'6時間30分',true,2 FROM q8 UNION ALL SELECT id,'7時間0分',false,3 FROM q8 UNION ALL SELECT id,'6時間0分',false,4 FROM q8),
c9  AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'1時間',false,1 FROM q9 UNION ALL SELECT id,'2時間',true,2 FROM q9 UNION ALL SELECT id,'3時間',false,3 FROM q9 UNION ALL SELECT id,'1時間30分',false,4 FROM q9),
c10 AS (INSERT INTO question_choices ("questionId",body,"isCorrect","displayOrder") SELECT id,'1時間',false,1 FROM q10 UNION ALL SELECT id,'1時間30分',true,2 FROM q10 UNION ALL SELECT id,'2時間',false,3 FROM q10 UNION ALL SELECT id,'1時間20分',false,4 FROM q10),
s2  AS (INSERT INTO question_steps ("questionId","stepNumber",body) SELECT id,1,'長い針が6のとき→30分、短い針が8のとき→8時 → 8時30分です。' FROM q2),
s3  AS (INSERT INTO question_steps ("questionId","stepNumber",body) SELECT id,1,'長い針が3のとき→15分（3×5＝15）、短い針が10のとき→10時 → 10時15分です。' FROM q3),
s6  AS (INSERT INTO question_steps ("questionId","stepNumber",body) SELECT id,1,'9時20分から40分前 → 20分から引けないので、9時からさかのぼります。9時－40分＝8時20分→ ×。20分前が8時40分、さらに20分前で8時40分です。' FROM q6),
s8  AS (INSERT INTO question_steps ("questionId","stepNumber",body) SELECT id,1,'8時30分から3時まで: 8時30分→12時は3時間30分、12時→3時は3時間 → 合計6時間30分です。' FROM q8)
SELECT 'time-basic done';
